# Copyright 2024 - TODAY, Escodoo
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

{
    "name": "Escodoo Setup Base",
    "summary": """
        Escodoo Odoo Setup Base""",
    "version": "16.0.1.0.0",
    "license": "AGPL-3",
    "author": "Escodoo",
    "website": "https://github.com/Escodoo/setup-addons",
    "depends": [
        "account",
        "account_analytic_required",
        "account_due_list",
        "account_edi",
        "account_edi_ubl_cii",
        "account_financial_report",
        "account_move_template",
        "account_move_tier_validation",
        "account_payment",
        "account_payment_invoice_online_payment_patch",
        "account_payment_mode",
        "account_payment_partner",
        "account_payment_purchase",
        "account_payment_purchase_stock",
        "account_payment_sale",
        "account_reconcile_oca",
        "account_sequence",
        "account_statement_base",
        "account_statement_import_base",
        "account_statement_import_file",
        "account_statement_import_file_reconcile_oca",
        "account_statement_import_ofx",
        "account_usability",
        "analytic",
        "auth_admin_passkey",
        # "auth_password_policy",
        # "auth_password_policy_portal",
        # "auth_password_policy_signup",
        "auth_signup",
        "auth_totp",
        "auth_totp_mail",
        "auth_totp_portal",
        "barcodes",
        "barcodes_gs1_nomenclature",
        "base",
        "base_address_extended",
        "base_automation",
        "base_import",
        "base_name_search_improved",
        "base_setup",
        "base_sparse_field",
        "base_technical_features",
        "base_tier_validation",
        "base_view_inheritance_extension",
        "bi_sql_editor",
        "board",
        "bus",
        "calendar",
        "contacts",
        "crm",
        "date_range",
        "date_range_account",
        "delivery",
        "delivery_carrier_partner",
        "digest",
        "disable_odoo_online",
        "hr",
        "hr_contract",
        "hr_employee_age",
        "hr_employee_relative",
        "hr_org_chart",
        "http_routing",
        "mail",
        "mail_debrand",
        "mis_builder",
        "mis_builder_cash_flow",
        "mis_template_financial_report",
        "partner_contact_access_link",
        # "password_security",
        "payment",
        "phone_validation",
        "portal",
        "product",
        "product_brand",
        "product_expiry",
        "product_net_weight",
        "purchase",
        "purchase_default_terms_conditions",
        "purchase_order_line_menu",
        "purchase_price_diff",
        "purchase_stock",
        "purchase_tier_validation",
        "remove_odoo_enterprise",
        "report_wkhtmltopdf_param",
        "report_xlsx",
        "report_xlsx_helper",
        "resource",
        "sale",
        "sale_crm",
        "sale_management",
        "sale_product_configurator",
        "sale_product_template_tags",
        "sale_purchase",
        "sale_purchase_stock",
        "sale_stock",
        "sale_stock_picking_invoicing",
        "sale_tier_validation",
        "sales_team",
        "scrap_reason_code",
        "server_action_mass_edit",
        "session_db",
        "spreadsheet",
        "spreadsheet_account",
        "spreadsheet_dashboard",
        "spreadsheet_dashboard_account",
        "spreadsheet_dashboard_purchase",
        "spreadsheet_dashboard_purchase_stock",
        "spreadsheet_dashboard_sale",
        "spreadsheet_dashboard_stock_account",
        "sql_request_abstract",
        "stock",
        "stock_account",
        "stock_analytic",
        "stock_landed_costs",
        "stock_picking_analytic",
        "stock_picking_invoice_link",
        "stock_picking_invoicing",
        "uom",
        "uom_alias",
        "utm",
        "web",
        "web_advanced_search",
        "web_dialog_size",
        "web_editor",
        "web_escodoo_brand",
        "web_kanban_gauge",
        "web_listview_range_select",
        "web_pwa_oca",
        "web_refresher",
        "web_responsive",
        "web_search_with_and",
        "web_theme_classic",
        "web_tour",
    ],
    # "installable": True,
}
